# Generated by Django 5.0.7 on 2025-02-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_vendor_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
